"""Shared state object for the LangGraph RAG pipeline.

``RAGState`` is a TypedDict passed between graph nodes. Each node reads some
keys, returns a partial dict, and LangGraph merges the result back into state.

Normative field definitions: ENTERPRISE_HYBRID_RAG_SPEC.md §6.
Developer guide: docs/DEVELOPER_GUIDE.md §4.
"""

from __future__ import annotations

from typing import Any, TypedDict


class RAGState(TypedDict, total=False):
    """Pipeline state for one research request.

    Keys are optional (``total=False``) because nodes populate them gradually.
    A novice can trace the query path by following which node sets each group.

    Request / scope — set by MCP tool or HTTP handler before the graph runs:
        query: Natural-language question from the user.
        tenant_id: Organization partition; required for ACL and Qdrant filter (FR-02).
        collection_id: Corpus to search within the tenant.
        document_id: Optional pin to a single document.
        version_id: Optional pin to one immutable ingest version.
        explicit_scope: True when the client pinned collection/document (skips supervisor).
        request_id: Correlation id for logs and optional result cache.
        langfuse_session_id / langfuse_trace_id: Observability hooks (IF-5).
        session_id: Conversation UUID for multi-turn history (§7.11).
        conversation_history: Prior user/assistant turns loaded from Postgres.
        query_dense_vector: Dense embed from inference (FR-13).
        query_sparse_vector: Sparse token indices/values for bm25-text.

    Pipeline outputs — produced by retrieve / rerank / answer nodes:
        scope_source: ``explicit`` or ``inferred`` after scope resolution.
        retrieved_chunks: Raw chunks from Qdrant before reranking.
        rerank_scores: Cross-encoder scores aligned with retrieved_chunks.
        context_blocks: Text blocks fed to the LLM after graph enrichment.
        sources: Citation list returned to the client (MCP Sources section).
        answer_text: Final grounded answer body.

    Control flags — routing and degradation:
        from_cache: True when check_cache returned a hit (skips retrieve path).
        abstained: True when rerank score is below threshold (FR-08); skips LLM.
        skip_supervisor: Dev/test flag to bypass query rewrite node.
        graph_enrich_enabled: When False, skip Neo4j enrichment (degrade L1).

    Observability:
        timings_ms: Per-stage wall time in milliseconds (FR-09).
        stub: True when this response was generated by stub logic, not live stores.
    """

    # Request / scope
    query: str
    tenant_id: str
    collection_id: str
    document_id: str | None
    version_id: str | None
    explicit_scope: bool
    request_id: str | None
    langfuse_session_id: str | None
    langfuse_trace_id: str | None
    session_id: str | None
    conversation_history: list[dict[str, str]]
    query_dense_vector: list[float]
    query_sparse_vector: dict[str, list]

    # Pipeline outputs
    scope_source: str
    retrieved_chunks: list[dict[str, Any]]
    rerank_scores: list[float]
    context_blocks: list[str]
    sources: list[dict[str, Any]]
    answer_text: str

    # Control flags
    from_cache: bool
    abstained: bool
    skip_supervisor: bool
    graph_enrich_enabled: bool
    degradation_level: str | None

    # Observability
    timings_ms: dict[str, int]
    stub: bool
